### EDA

In [6]:
#importing pandas lib
import pandas as pd

In [7]:
#installing pandas package
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
#importing dataset
df= pd.read_csv("customer_shopping_behavior.csv")

In [9]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [11]:
#checking the null count
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [13]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [14]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [15]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [16]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_column',None)
pd.set_option('display.max_rows',None)

In [17]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [18]:
category_mapping = {
    #Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Backpack": "Accessories",
    "Belt": "Accessories",
    "Scarf": "Accessories",
    "Bag": "Accessories",
    #Clothing
    "T-shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",
    "Shirt": "Clothing",
    #Footwear
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",
    "Shoes": "Footwear",
    #Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear",
    #Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Watch": "Electronics",
    "Headphones": "Electronics",
}

In [19]:
df['Category']=df['Item Purchased'].map(category_mapping)

In [20]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [38]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear       [Not Applicable]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

### Filling null values

In [23]:
#treating null values or replacing value in Electronics Category
df.loc[df['Category'] == 'Electronics','Size'] = "Not Applicable"

In [30]:
#treating null values or replacing value in Accessories Category
df.loc[df['Category'] == 'Accessories','Size'] = "Free Size"

In [34]:
#treating null values or replacing value in Footwear Category
df.loc[df['Category'] == 'Footwear','Size'] = "Not Applicable"

In [37]:
#treating null values or replacing value in Clothing Category
df.loc[(df['Category']=='Clothing') & (df['Size'].isnull()),"Size"]=df[df['Category']=='Clothing']['Size'].mode()[0]

In [41]:
#filling null values of review ratings with mean of item purchased 
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [52]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [45]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,Free Size,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,Free Size,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,Free Size,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly

In [44]:
df['Review Rating'] = df['Review Rating'].round(2)

### Previous Purchases

In [46]:
#filing Previous Purchases with 0
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

### Purchase Amount (USD)

In [50]:
df.groupby('Item Purchased')['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [51]:
#filling null values of Purchase Amount (USD) with mean of item purchased 
df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

### Checking Duplicate Records

In [58]:
df.duplicated().sum()

np.int64(50)

In [59]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not Applicable,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not Applicable,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free Size,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free Size,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free Size,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free Size,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free Size,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free Size,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free Size,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free Size,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,Not Applicable,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,Not Applicable,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,Not Applicable,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free Size,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free Size,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,Not Applicable,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free Size,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free Size,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free Size,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free Size,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,Not Applicable,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free Size,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free Size,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,Not Applicable,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

In [61]:
#Deleting Duplicate Records
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [62]:
len(df)

5000

In [63]:
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      5000
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

In [72]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

### Renaming the Headers

In [66]:
df.columns = df.columns.str.replace(" ","_")
df.columns = df.columns.str.lower()

In [71]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [70]:
 #replacing purchase_amount_(usd) with purchase_amount
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

### Connection to sql server

In [76]:
!pip install pyodbc sqlalchemy

Collecting pyodbc
  Using cached pyodbc-5.3.0-cp39-cp39-win_amd64.whl.metadata (2.8 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.14.1)
Using cached pyodbc-5.3.0-cp39-cp39-win_amd64.whl (69 kB)
Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build installable wheels for some pyproject.toml based projects (greenlet)

In [5]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("postgresql://avi:avinash@10@localhost:5432/customer_db")

df = pd.read_sql("SELECT * FROM your_table", engine)
df.head()

OperationalError: (psycopg2.OperationalError) could not translate host name "10@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [78]:
!pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.14.1)
Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build installable wheels for some pyproject.toml based projects (greenlet)

In [2]:
import sys
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.14.1)
Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Failed to build installable wheels for some pyproject.toml based projects (greenlet)

In [3]:
!python -m pip install --upgrade pip
!pip install sqlalchemy psycopg2-binary --only-binary :all:

Requirement already satisfied: pip in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (25.1.1)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 645.7 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 645.7 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 645.7 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 486.4 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 592.2 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 592.2 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 651.3 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 687.7 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 707.6 kB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Successfully installed pip-26.0.1
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp39-cp39-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.14.1)
Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Downloading greenlet-3.2.4-cp39-cp39-win_amd64.whl (298 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.2.4 psycopg2-binary-2.9.12 sqlalchemy-2.0.49